  stage: build
  environment: $ENVIRONMENT
  tags:
    - ita-shell-builder
  before_script:
     - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script: 
    - docker build -t $IMAGE_NAME . --progress=plain
    - docker push $IMAGE_NAME
  after_script:
    - docker logout $CI_REGISTRY
    - docker image prune -f
   
